# Generated by Django 5.1.3 on 2025-01-17 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ordem', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Contador',
            fields=[
                ('id_salvo', models.AutoField(primary_key=True, serialize=False)),
                ('data_execucao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Execução')),
                ('observacoes', models.CharField(max_length=100, verbose_name='Observacões')),
            ],
        ),
        migrations.CreateModel(
            name='Quadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo_operacao', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saida')], max_length=15, verbose_name='Tipo do operação')),
                ('cliente_fornecedor', models.CharField(blank=True, default='', max_length=150, verbose_name='Cliente/Fornecedor')),
                ('descricao', models.CharField(blank=True, max_length=150)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consolidado', models.BooleanField(default=False)),
                ('id_consolidacao', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.categoria', verbose_name='Categoria')),
            ],
            options={
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsavel', models.CharField(max_length=100, verbose_name='Responsavel')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('quadra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.quadra')),
            ],
        ),
    ]
