# Generated by Django 5.1.3 on 2025-01-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixa',
            name='cliente_fornecedor',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Cliente/Fornecedor'),
        ),
    ]
