# Generated by Django 5.1.3 on 2025-02-02 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Parceiro')),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('cidade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cidade e Estado')),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('cep', models.CharField(blank=True, max_length=12, null=True, verbose_name='CEP')),
                ('ativo', models.BooleanField(default=True)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='CNPJ')),
                ('ie', models.CharField(blank=True, max_length=14, null=True, verbose_name='Inscrição Estadual')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='caixa',
            options={'ordering': ['-data']},
        ),
        migrations.RemoveField(
            model_name='caixa',
            name='cliente_fornecedor',
        ),
        migrations.AlterField(
            model_name='caixa',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financas.categoria', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='caixa',
            name='parceiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financas.parceiro', verbose_name='Parceiro'),
        ),
    ]
