# Generated by Django 5.1.3 on 2025-01-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0002_parceiro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parceiro',
            old_name='cpf',
            new_name='cpf_cnpj',
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Parceiro'),
        ),
    ]
