# Generated by Django 5.1.3 on 2025-01-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0003_rename_cpf_parceiro_cpf_cnpj_alter_parceiro_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='parceiro',
            name='ie',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='Inscrição Estadual'),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='cidade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cidade e Estado'),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CNPJ'),
        ),
    ]
