# Generated by Django 5.1.3 on 2025-01-29 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0004_parceiro_ie_alter_parceiro_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceiro',
            name='cep',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='CNPJ'),
        ),
    ]
