# Generated by Django 5.1.3 on 2025-01-30 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0005_alter_parceiro_cep_alter_parceiro_cpf_cnpj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caixa',
            name='cliente_fornecedor',
        ),
        migrations.AddField(
            model_name='caixa',
            name='parceiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financas.parceiro', verbose_name='Parceiro'),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financas.categoria', verbose_name='Categoria'),
        ),
    ]
