# Generated by Django 5.1.3 on 2025-01-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0006_remove_caixa_cliente_fornecedor_caixa_parceiro_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caixa',
            options={'ordering': ['-data']},
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='ie',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Inscrição Estadual'),
        ),
    ]
