# Generated by Django 5.1.3 on 2025-01-17 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('data_admisao', models.DateField(blank=True, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('cidade', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('ativo', models.BooleanField(default=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_socios/')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('tipo_socio', models.CharField(choices=[('remido', 'Remido'), ('patrimonial', 'Patrimonial'), ('benemerito', 'Benemérito'), ('contribuinte', 'Contribuinte')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Dependente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do dependente')),
                ('parentesco', models.CharField(choices=[('conjuge', 'Conjuge'), ('filho', 'Filho(a)'), ('enteado', 'Enteado(a)'), ('sobrinho', 'Sobrinho(a)'), ('outro', 'Outro')], max_length=50)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_dependentes/')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependentes', to='socios.socio')),
            ],
        ),
        migrations.CreateModel(
            name='Mensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(default=2025, verbose_name='Mensalidade do ano')),
                ('jan', models.BooleanField(default=False)),
                ('fev', models.BooleanField(default=False)),
                ('mar', models.BooleanField(default=False)),
                ('abr', models.BooleanField(default=False)),
                ('mai', models.BooleanField(default=False)),
                ('jun', models.BooleanField(default=False)),
                ('jul', models.BooleanField(default=False)),
                ('ago', models.BooleanField(default=False)),
                ('set', models.BooleanField(default=False)),
                ('out', models.BooleanField(default=False)),
                ('nov', models.BooleanField(default=False)),
                ('dez', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensalidades', to='socios.socio')),
            ],
            options={
                'ordering': ['socio', 'ano'],
                'unique_together': {('socio', 'ano')},
            },
        ),
    ]
