# Generated by Django 5.1.3 on 2025-01-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dependente',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='socio',
            options={'ordering': ['nome']},
        ),
        migrations.RemoveField(
            model_name='socio',
            name='estado',
        ),
        migrations.AddField(
            model_name='socio',
            name='esporte',
            field=models.CharField(blank=True, choices=[('beachtennis', 'BeachTennis'), ('cartas', 'Cartas'), ('futebol', 'Futebol'), ('voleibol', 'Voleibol'), ('nenhum', 'Nenhum')], max_length=15, null=True, verbose_name='Esporte Preferido'),
        ),
        migrations.AddField(
            model_name='socio',
            name='num_titulo',
            field=models.CharField(blank=True, default='000', max_length=3, null=True, verbose_name='Numero Titulo'),
        ),
        migrations.AddField(
            model_name='socio',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observacões'),
        ),
        migrations.AlterField(
            model_name='dependente',
            name='parentesco',
            field=models.CharField(choices=[('esposa', 'Esposa'), ('esposo', 'Esposo'), ('filha', 'Filha'), ('filho', 'Filho'), ('enteada', 'Enteada'), ('enteado', 'Enteado'), ('mae', 'Mãe'), ('pai', 'Pai'), ('outro', 'Outro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='socio',
            name='cidade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cidade/Estado'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='tipo_socio',
            field=models.CharField(choices=[('patrimonial', 'Patrimonial'), ('contribuinte', 'Contribuinte'), ('remido', 'Remido'), ('benemerito', 'Benemérito')], max_length=15),
        ),
    ]
