# Generated by Django 5.1.3 on 2025-01-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_alter_dependente_options_alter_socio_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='endereco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
