# Generated by Django 5.1.3 on 2025-01-29 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_alter_dependente_options_alter_socio_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='cep',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='CEP'),
        ),
    ]
