# Generated by Django 5.1.3 on 2025-01-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0003_alter_socio_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='num_titulo',
            field=models.CharField(blank=True, default='000', max_length=4, null=True, verbose_name=''),
        ),
    ]
