# Generated by Django 5.1.3 on 2025-01-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0004_alter_socio_num_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='num_titulo',
            field=models.CharField(blank=True, default='000', max_length=4, null=True, verbose_name='Numero Titulo'),
        ),
    ]
