# Generated by Django 5.1.3 on 2025-01-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0006_alter_socio_num_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='esporte',
            field=models.CharField(blank=True, choices=[('beachtennis', 'BeachTennis'), ('cartas', 'Cartas'), ('futebol', 'Futebol'), ('voleibol', 'Voleibol'), ('nenhum', 'Nenhum')], max_length=15, null=True, verbose_name='Esporte Preferido'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
