# Generated by Django 5.1.3 on 2025-01-01 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_nome_completo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nome_completo',
        ),
    ]
